2025-01-24 16:18:33,039 - Darshan is getting AttributeError on accessing send_test_email: 'function' object has no attribute 'email_signature'
2025-01-25 10:59:08,544 - Darshan is getting IntegrityError on accessing edit_user: NOT NULL constraint failed: App1_user.account_lock
2025-01-26 12:17:41,119 - Darshan is getting RuntimeError on accessing save_equipment_settings: b' TCP : Unreachable peer'
2025-01-26 12:17:41,613 - Darshan is getting RuntimeError on accessing save_equipment_settings: b' TCP : Unreachable peer'
2025-01-27 13:32:48,429 - Darshan is getting OperationalError on accessing admin:App1_smsalert_changelist: no such table: App1_smsalert
2025-01-27 13:32:56,764 - Darshan is getting OperationalError on accessing admin:App1_smsalert_changelist: no such table: App1_smsalert
2025-01-27 13:33:19,106 - Darshan is getting OperationalError on accessing admin:App1_emailalert_changelist: no such table: App1_emailalert
2025-01-27 13:33:39,822 - Darshan is getting OperationalError on accessing admin:App1_smsalert_changelist: no such table: App1_smsalert
2025-01-27 18:25:14,228 - Sunwell is getting AttributeError on accessing user_activity: 'SuperAdmin' object has no attribute 'department'
2025-01-27 18:27:08,152 - Sunwell is getting AttributeError on accessing user_activity: 'SuperAdmin' object has no attribute 'department'
2025-01-27 18:46:48,600 - Darshan is getting TemplateSyntaxError on accessing equipment_configure: Invalid block tag on line 216: 'enif', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2025-01-28 18:52:53,004 - Darshan is getting TypeError on accessing download_backup: cannot unpack non-iterable NoneType object
2025-01-28 18:57:46,590 - Darshan is getting ValueError on accessing equipment_configure: Field 'total_temp_sensors' expected a number but got ''.
2025-01-28 18:58:34,020 - Darshan is getting ValueError on accessing equipment_configure: Field 'total_temp_sensors' expected a number but got ''.
2025-01-30 10:46:59,219 - Sunwell is getting AttributeError on accessing view_log: 'SuperAdmin' object has no attribute 'department'
2025-01-30 10:53:29,164 - Sunwell is getting AttributeError on accessing view_log: 'SuperAdmin' object has no attribute 'department'
2025-01-30 10:59:17,176 - Sunwell is getting AttributeError on accessing view_log: 'NoneType' object has no attribute 'footer_note'
2025-01-30 14:51:25,721 - Sunwell is getting AttributeError on accessing Equipment_Audit_log: 'SuperAdmin' object has no attribute 'department'
2025-01-30 15:02:50,835 - Sunwell is getting AttributeError on accessing alaram_Audit_log: 'function' object has no attribute 'header_note'
2025-01-30 15:04:21,018 - Sunwell is getting AttributeError on accessing email_Audit_log: 'SuperAdmin' object has no attribute 'department'
2025-01-30 15:05:16,837 - Sunwell is getting AttributeError on accessing email_Audit_log: 'NoneType' object has no attribute 'header_note'
2025-01-30 15:06:26,352 - Sunwell is getting NameError on accessing email_Audit_log: 
handle_pageBegin args=() name 'department_name' is not defined
2025-01-30 15:11:21,725 - Sunwell is getting AttributeError on accessing sms_Audit_log: 'NoneType' object has no attribute 'header_note'
2025-02-02 11:12:35,403 - Darshan is getting NameError on accessing department: name 'ValidationError' is not defined
2025-02-04 16:12:35,460 - Darshan is getting TypeError on accessing Mkt_analysis: Mkt_analysis() missing 9 required positional arguments: 'records', 'from_date', 'to_date', 'from_time', 'to_time', 'organization', 'department', 'username', and 'selected_equipment'
2025-02-04 16:13:25,791 - Darshan is getting TypeError on accessing Mkt_analysis: Mkt_analysis() missing 8 required positional arguments: 'from_date', 'to_date', 'from_time', 'to_time', 'organization', 'department', 'username', and 'selected_equipment'
2025-02-04 16:13:57,001 - Darshan is getting TypeError on accessing Mkt_analysis: strptime() argument 1 must be str, not None
2025-02-04 16:17:21,341 - Darshan is getting TypeError on accessing Mkt_analysis: strptime() argument 1 must be str, not None
2025-02-04 16:19:09,809 - Darshan is getting AttributeError on accessing Mkt_analysis: 'function' object has no attribute 'exists'
2025-02-04 16:24:28,531 - Darshan is getting TypeError on accessing Mkt_analysis: 
handle_pageBegin args=() generate_mkt_log_pdf.<locals>.create_page() takes 1 positional argument but 2 were given
2025-02-04 16:25:58,679 - Darshan is getting DoesNotExist on accessing Mkt_analysis: 
handle_pageBegin args=() Equipment matching query does not exist.
2025-02-04 16:31:35,201 - Darshan is getting DoesNotExist on accessing Mkt_analysis: 
handle_pageBegin args=() Equipment matching query does not exist.
2025-02-04 16:31:50,739 - Darshan is getting DoesNotExist on accessing Mkt_analysis: 
handle_pageBegin args=() Equipment matching query does not exist.
2025-02-04 16:32:08,171 - Darshan is getting DoesNotExist on accessing Mkt_analysis: 
handle_pageBegin args=() Equipment matching query does not exist.
2025-02-04 16:35:16,196 - Darshan is getting DoesNotExist on accessing Mkt_analysis: 
handle_pageBegin args=() Equipment matching query does not exist.
2025-02-04 17:02:16,238 - Darshan is getting FieldError on accessing Mkt_analysis: Cannot resolve keyword 'equipment' into field. Choices are: date, equip_name, equip_name_id, id, rh_1, rh_10, rh_2, rh_3, rh_4, rh_5, rh_6, rh_7, rh_8, rh_9, rh_high_alarm, rh_high_alert, rh_low_alarm, rh_low_alert, set_rh, set_temp, t_high_alarm, t_high_alert, t_low_alarm, t_low_alert, time, tmp_1, tmp_10, tmp_2, tmp_3, tmp_4, tmp_5, tmp_6, tmp_7, tmp_8, tmp_9
2025-02-04 18:16:54,903 - Darshan is getting TypeError on accessing Mkt_analysis: generate_mkt_log_pdf() missing 2 required positional arguments: 'selected_equipment' and 'results'
2025-02-04 18:18:33,434 - Darshan is getting TypeError on accessing Mkt_analysis: generate_mkt_log_pdf() missing 2 required positional arguments: 'selected_equipment' and 'results'
2025-02-04 18:18:48,616 - Darshan is getting TypeError on accessing Mkt_analysis: generate_mkt_log_pdf() missing 2 required positional arguments: 'selected_equipment' and 'results'
2025-02-04 18:20:25,284 - Darshan is getting NameError on accessing Mkt_analysis: name 'from_time' is not defined
2025-02-04 18:20:47,663 - Darshan is getting NameError on accessing Mkt_analysis: 
handle_pageBegin args=() name 'from_time' is not defined
2025-02-04 18:21:49,113 - Darshan is getting IndexError on accessing Mkt_analysis: 
spanning problem in <Table@0x207B7B3D340 11 rows x 4 cols(tallest row 27)> with cell(0,0) containing
'Channel' list index out of range
2025-02-05 13:44:19,354 - Darshan is getting TemplateSyntaxError on accessing Mkt_analysis: Invalid block tag on line 186: 'endfor', expected 'endblock'. Did you forget to register or load this tag?
2025-02-05 13:45:12,952 - Darshan is getting TypeError on accessing Mkt_analysis: 'int' object is not iterable
2025-02-05 13:48:13,603 - Darshan is getting UnboundLocalError on accessing Mkt_analysis: cannot access local variable 'eqp_sensor' where it is not associated with a value
2025-02-05 16:05:21,936 - Anonymous is getting UnboundLocalError on accessing login: cannot access local variable 'user' where it is not associated with a value
2025-02-05 16:05:36,315 - Anonymous is getting UnboundLocalError on accessing login: cannot access local variable 'user' where it is not associated with a value
2025-02-05 16:08:55,690 - Anonymous is getting TypeError on accessing login: 'int' object is not subscriptable
2025-02-07 12:00:37,207 - Darshan is getting TemplateSyntaxError on accessing Mkt_analysis: Invalid filter: 'dict'
2025-02-07 12:01:16,153 - Darshan is getting TemplateSyntaxError on accessing Mkt_analysis: Invalid filter: 'dict'
2025-02-07 12:01:17,823 - Darshan is getting TemplateSyntaxError on accessing Mkt_analysis: Invalid filter: 'dict'
2025-02-07 12:01:20,793 - Darshan is getting TemplateSyntaxError on accessing Mkt_analysis: Invalid filter: 'dict'
2025-02-07 12:18:01,563 - Darshan is getting TemplateSyntaxError on accessing Mkt_analysis: Could not parse the remainder: '(equipment.total_temp_sensors)' from 'range(equipment.total_temp_sensors)'
2025-02-07 12:18:03,257 - Darshan is getting TemplateSyntaxError on accessing Mkt_analysis: Could not parse the remainder: '(equipment.total_temp_sensors)' from 'range(equipment.total_temp_sensors)'
2025-02-07 12:18:03,667 - Darshan is getting TemplateSyntaxError on accessing Mkt_analysis: Could not parse the remainder: '(equipment.total_temp_sensors)' from 'range(equipment.total_temp_sensors)'
2025-02-07 12:18:03,835 - Darshan is getting TemplateSyntaxError on accessing Mkt_analysis: Could not parse the remainder: '(equipment.total_temp_sensors)' from 'range(equipment.total_temp_sensors)'
2025-02-08 10:48:15,205 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 10:50:37,185 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 10:50:41,160 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 10:54:14,103 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 10:54:21,424 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:09:15,678 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:20:32,298 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:20:34,990 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:20:52,079 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:35:28,691 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:35:31,296 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:36:18,169 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:36:32,560 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:36:56,180 - Prasanna is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:40:49,609 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 11:40:51,144 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\LOGO_JPEG_-_Copy.jpg” does not exist
2025-02-08 12:19:01,235 - Darshan is getting AttributeError on accessing Mkt_analysis: 'NumberedCanvas' object has no attribute 'pages'
2025-02-08 12:21:43,553 - Darshan is getting AttributeError on accessing Mkt_analysis: 'NumberedCanvas' object has no attribute 'pages'
2025-02-08 12:33:54,649 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:35:00,707 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:37:33,305 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:37:34,312 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:37:34,673 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:37:35,056 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:37:35,410 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:42:25,232 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:42:26,407 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:42:27,121 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:42:27,776 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:42:28,468 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:42:31,753 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'date'
2025-02-08 12:44:37,416 - Darshan is getting TypeError on accessing Mkt_analysis: generate_mkt_log_pdf.<locals>.mkt_table() takes 0 positional arguments but 1 was given
2025-02-08 12:45:54,795 - Darshan is getting AttributeError on accessing Mkt_analysis: 'dict' object has no attribute 'time'
2025-02-08 12:46:38,675 - Darshan is getting KeyError on accessing Mkt_analysis: 'time'
2025-02-08 12:47:40,703 - Darshan is getting NameError on accessing Mkt_analysis: 
handle_pageBegin args=() cannot access free variable 'records_from_time' where it is not associated with a value in enclosing scope
2025-02-08 12:52:44,389 - Darshan is getting KeyError on accessing Mkt_analysis: 'startdate'
2025-02-08 13:42:43,904 - Darshan is getting TypeError on accessing Mkt_analysis: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U1'), dtype('<U1'), dtype('<U2'))
2025-02-08 13:43:26,323 - Darshan is getting TypeError on accessing Mkt_analysis: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U1'), dtype('<U1'), dtype('<U2'))
2025-02-08 13:53:39,356 - Darshan is getting DoesNotExist on accessing Mkt_analysis: Equipment matching query does not exist.
2025-02-08 18:34:17,573 - Darshan is getting IndexError on accessing Mkt_analysis: list assignment index out of range
2025-02-10 18:47:26,946 - Darshan is getting OSError on accessing Mkt_analysis: 
handle_pageBegin args=() Cannot open resource "D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\iiiQ_-_logo_Yl3uP17.png"
2025-02-10 18:54:18,238 - Darshan is getting IndexError on accessing Mkt_analysis: 
spanning problem in <Table@0x1A958E04320 12 rows x 18 cols(tallest row 27)> with cell(0,0) containing
'Rec No' list index out of range
2025-02-10 19:02:37,828 - Darshan is getting IndexError on accessing Mkt_analysis: 
spanning problem in <Table@0x1DC9635AF30 12 rows x 18 cols(tallest row 27)> with cell(0,0) containing
'Rec No' list index out of range
2025-02-11 09:38:41,820 - Darshan is getting IndexError on accessing Mkt_analysis: 
spanning problem in <Table@0x21E5E66BE00 12 rows x 18 cols(tallest row 27)> with cell(0,0) containing
'Rec No' list index out of range
2025-02-11 11:49:50,130 - Darshan is getting AttributeError on accessing Mkt_analysis: 'NumberedCanvas' object has no attribute 'pages'
2025-02-11 12:00:07,772 - Darshan is getting TypeError on accessing Mkt_analysis: 'list' object cannot be interpreted as an integer
2025-02-11 12:01:06,757 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 12:01:11,312 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 12:01:12,065 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 12:01:31,695 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 12:03:06,362 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 12:03:58,804 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 12:06:08,729 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 12:06:49,983 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 12:08:35,578 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 14:03:21,599 - Darshan is getting ValueError on accessing equipment_configure: Field 'total_temp_sensors' expected a number but got ''.
2025-02-11 15:18:54,325 - Darshan is getting IntegrityError on accessing equipment_edit: UNIQUE constraint failed: App1_plcuser.code
2025-02-11 15:23:33,996 - Darshan is getting IntegrityError on accessing equipment_edit: UNIQUE constraint failed: App1_plcuser.code
2025-02-11 15:55:26,755 - Darshan is getting IndexError on accessing Mkt_analysis: list index out of range
2025-02-11 15:59:07,594 - Darshan is getting TypeError on accessing Mkt_analysis: 'list' object cannot be interpreted as an integer
2025-02-11 16:30:12,360 - Darshan is getting TypeError on accessing Mkt_analysis: 'int' object is not iterable
2025-02-11 17:01:55,266 - Darshan is getting IndexError on accessing Mkt_analysis: 
spanning problem in <Table@0x27E566FE1E0 12 rows x 33 cols(tallest row 27)> with cell(0,0) containing
'Rec No' list index out of range
2025-02-11 17:30:02,437 - Darshan is getting UnboundLocalError on accessing view_log: cannot access local variable 'equipment' where it is not associated with a value
2025-02-12 13:22:25,280 - Darshan is getting TypeError on accessing Mkt_analysis: can't multiply sequence by non-int of type 'list'
2025-02-12 16:43:06,717 - Darshan is getting Error on accessing comm_group: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
2025-02-12 16:54:52,122 - Darshan is getting TypeError on accessing equipment_configure: Organization.get_nod() missing 1 required positional argument: 'self'
2025-02-12 17:03:03,281 - Darshan is getting NameError on accessing equipment_configure: name 'eqp' is not defined
2025-02-12 17:03:29,535 - Darshan is getting NameError on accessing equipment_configure: name 'eqp' is not defined
2025-02-12 17:03:30,381 - Darshan is getting NameError on accessing equipment_configure: name 'eqp' is not defined
2025-02-12 17:03:33,276 - Darshan is getting NameError on accessing equipment_configure: name 'eqp' is not defined
2025-02-13 11:48:03,866 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:42,300 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:48,798 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:49,443 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:49,817 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:50,016 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:52,702 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:53,889 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:54,339 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:54,721 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:55,084 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:55,423 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:48:55,980 - Darshan is getting TemplateSyntaxError on accessing user_access: Could not parse the remainder: '(data.role' from '(data.role'
2025-02-13 11:49:28,940 - Darshan is getting TemplateSyntaxError on accessing user_access: Invalid block tag on line 217: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2025-02-13 16:47:15,526 - Sunwell is getting AttributeError on accessing backup: module 'django.contrib.messages' has no attribute 'erro'
2025-02-13 16:48:06,086 - Sunwell is getting AttributeError on accessing backup: module 'django.contrib.messages' has no attribute 'erro'
2025-02-13 18:25:40,187 - Sunwell is getting TemplateSyntaxError on accessing dashboard: Could not parse the remainder: ' Admin' from 'Super Admin'
2025-02-13 18:26:04,660 - Sunwell is getting TemplateSyntaxError on accessing dashboard: Empty variable tag on line 623
2025-02-14 16:33:01,618 - Sunwell is getting AttributeError on accessing backup: module 'django.contrib.messages' has no attribute 'erro'
2025-02-14 17:01:54,996 - Darshan is getting AttributeError on accessing edit_backup: type object 'datetime.datetime' has no attribute 'datetime'
2025-02-14 17:02:53,083 - Darshan is getting AttributeError on accessing edit_backup: type object 'datetime.datetime' has no attribute 'datetime'
2025-02-14 17:46:43,867 - Darshan is getting Http404 on accessing django.views.static.serve: “D:\iiiQbets\2024\Projects\Sunwell Technologies\New folder (2)\Sunwell\Sunwell\media\iiiQ_-_logo_Lt7Vx2V.png” does not exist
